version: 1.1.0.{build}-beta
image: Visual Studio 2017
configuration: Release
environment:
  CAKE_SETTINGS_SKIPVERIFICATION: true
  ANDROID_HOME: 'C:\Program Files (x86)\Android\android-sdk\'
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build_script:
- cmd: >-
    powershell .\build_library_and_run_cake.ps1
artifacts:
- path: ./Build/nuget/*.nupkg
  name: NuGet
